name: Test Deploy SSH (fixed)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      out-path: out
    steps:
      - name: Create dummy site
        run: |
          mkdir -p out
          cat > out/index.html <<'HTML'
          <!doctype html>
          <html>
            <head><meta charset="utf-8"><title>Test Deploy</title></head>
            <body><h1>Hello from GitHub Actions 🚀</h1></body>
          </html>
          HTML

      - name: Show out/ contents
        run: ls -la out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # copy the built files into the workspace so the upload step can find them
      - name: Copy out/ from build (workspace)
        run: |
          # build job produced out/ in the same workspace on the runner
          # if your real build is in the same job you won't need this
          ls -la out || true

      # Check secrets at run-time (secrets are safe to reference inside 'run')
      - name: Check SSH secrets presence
        id: check
        run: |
          # Use environment variables set from secrets for clarity
          echo "SSH_HOST='${{ secrets.SSH_HOST }}'"
          if [ -n "${{ secrets.SSH_HOST }}" ] && \
             [ -n "${{ secrets.SSH_USER }}" ] && \
             [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ] && \
             [ -n "${{ secrets.SSH_TARGET }}" ]; then
            echo "upload=true" >> $GITHUB_OUTPUT
          else
            echo "upload=false" >> $GITHUB_OUTPUT
          fi

      - name: Debug check output
        run: echo "upload=${{ steps.check.outputs.upload }}"

      - name: Upload via SCP
        if: ${{ steps.check.outputs.upload == 'true' }}
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          source: "out/*"
          target: ${{ secrets.SSH_TARGET }}

      - name: Skip upload message
        if: ${{ steps.check.outputs.upload != 'true' }}
        run: |
          echo "SSH secrets missing or empty. To enable upload, add SSH_HOST, SSH_USER, SSH_PRIVATE_KEY and SSH_TARGET in Repository → Settings → Secrets."
